### PR TITLE
Fix billing dropdown selection and return Stripe plans from billing service.

### LINKED ISSUE #398: Billing Plan dropdown is empty on tenant onboarding screen
Billing Plan dropdown is empty on tenant onboarding screen.

### Reproduction Steps

Go to SaaS Boost admin ui.
Go to onboarding screen.
Click provision tenant.
Check Billing plan dropdown values

### What did you expect to happen?

Billing Plan dropdown should have values

### What actually happened?

Billing Plan dropdown does not show any values even though BillingProvider Key is set and there are plans available in Billing API and products available in Stripe.

### Environment

  - **AWS Region  :us-east-1
  - **AWS SaaS Boost Version :v2.0.0-18-dirty@13077ec
  - **Workload OS  (Linux or Windows) :Linux

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by PoeppingT**
Fixes #398 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: metering-billing/lambdas/src/main/java/com/amazon/aws/partners/saasfactory/metering/common/BillingUtils.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+        try {
+            String responseBody = ApiGatewayHelper.signAndExecuteApiRequest(
+                    apiRequest, apiGatewayRole, "BillingIntegration");
+            Map<String, String> setting = Utils.fromJson(responseBody, HashMap.class);
+            if (null == setting) {
+                throw new RuntimeException("responseBody is invalid");
+            }            
+            apiKey = setting.get("value");
+        } catch (Exception e) {
+            LOGGER.error("getBillingApiKey: Error invoking API settings/BILLING_API/ref");
```
Comment (brtrvn) [inline metering-billing/lambdas/src/main/java/com/amazon/aws/partners/saasfactory/metering/common/BillingUtils.java:51]: We should change the error message to match the actual endpoint that failed `settings/BILLING_API_KEY/secret`

File: metering-billing/lambdas/src/main/java/com/amazon/aws/partners/saasfactory/metering/onboarding/SubscriptionService.java [hunk 2]
```diff
@@ -24,49 +25,78 @@
...
 
-        //Utils.logRequestEvent(event);
-        APIGatewayProxyResponseEvent response = null;
-        ArrayNode plans = JsonNodeFactory.instance.arrayNode();
-        for (SubscriptionPlan plan : SubscriptionPlan.values()) {
-            ObjectNode planN = JsonNodeFactory.instance.objectNode();
-            planN.put("planId", plan.name());
-            planN.put("planName", plan.getLabel());
-            plans.add(planN);
+        Stripe.apiKey = BillingUtils.getBillingApiKey(API_GATEWAY_HOST, API_GATEWAY_STAGE, API_TRUST_ROLE);
```
Comment (brtrvn) [inline metering-billing/lambdas/src/main/java/com/amazon/aws/partners/saasfactory/metering/onboarding/SubscriptionService.java:67]: Note that this can throw an `java.util.NoSuchElementException: No value present` if app config doesn't have a billing api key or if app config simply hasn't been saved yet. A better client experience would be to return either an empty list or a `404` when no plans exist. However, there is no way to invoke this API through the admin web app until you've saved the app config, so impact right now is very minimal.

**Review by brtrvn — CHANGES_REQUESTED** [review]
Resolves the immediate issue of being able to select one of the (hard coded) pre-defined billing plans during tenant onboarding. We should rebase to `main` and tweak an error message for clarity. Tracking issues on actually subscribing the tenant as a Stripe customer to the selected billing plan elsewhere.

**Review by brtrvn — APPROVED** [review]
LGTM
